### ISSUE TITLE
Documentation builds on ReadTheDocs are failing

### ISSUE THREAD

**Issue by mmuckley** [facebookresearch/NeuralCompression#140]
## Bug

Documentation builds on ReadTheDocs are failing.

## Steps

See here: https://readthedocs.org/projects/neuralcompression/builds/15172473/

## Expected behavior

Docs should build without error.

## Environment

ReadTheDocs

## Context

See here: https://readthedocs.org/projects/neuralcompression/builds/15172473/

**Comment by 0x00b1** [comment]
@mmuckley Would you mind granting me permission to the RTD project?

**Comment by mmuckley** [comment]
@0x00b1 what is your RTD username?

**Comment by mmuckley** [comment]
@0x00b1 done.

**Comment by 0x00b1** [comment]
Thanks @mmuckley!

**Comment by 0x00b1** [comment]
Fixed @mmuckley. Feel free to close this issue after you verify. 😄
