### ISSUE TITLE
Upstream Google autoencoder models to CompressAI

### ISSUE THREAD

**Issue by mmuckley** [facebookresearch/NeuralCompression#188]
At the moment we have several model implementations that are already implemented in [CompressAI](https://github.com/InterDigitalInc/CompressAI) (e.g., Scale Hyperprior, Mean-Scale Hyperprior). At this point CompressAI has pretty good adoption, so we should be able to remove these from our repository and upstream the dependency.

By default CompressAI doesn't handle reflective image padding for users, so if desired we could include wrappers like that in PR #185 to handle this for users unfamiliar with the functionality of these models.

**Comment by desi-ivanova** [comment]
Happy to help with that at some point.

Padding and image standardization (to 0-1 range) -- both of which are supposed to be handled by the user (described in the second to last paragraph in compressai documentation [here](https://interdigitalinc.github.io/CompressAI/zoo.html#image-compression)) -- can be handled by wrappers instead, as you suggest.

**Comment by mmuckley** [comment]
Addressed in PR #196.
